spring.datasource.url=postgresql://biblioteca_4rkn_user:9LNSYRg6H5udQNlE6ZDn0Lg0FboFw3li@dpg-dav69efpn0mc73abo2ng-a/biblioteca_4rkn
spring.datasource.username=biblioteca_4rkn_user
spring.datasource.password=9LNSYRg6H5udQNlE6ZDn0Lg0FboFw3li
spring.jpa.hibernate.ddl-auto=update